# =================================================================== 
# Environment
# =================================================================== 
env: prod


# =================================================================== 
# Jekyll PROD configuration 
# =================================================================== 
include: [.htaccess]
destination: ./prod


# =================================================================== 
# Jekyll-Assets PROD configuration 
# =================================================================== 
assets:
    js_compressor: yui
    cachebust: none