# =================================================================== 
# Environment
# =================================================================== 
env: dev


# =================================================================== 
# Jekyll DEV configuration 
# =================================================================== 
destination: ./dev


# =================================================================== 
# Jekyll-Assets DEV configuration 
# =================================================================== 
assets:
    cachebust: soft